name: $(Build.SourceBranchName)_$(Build.BuildId)_$(Date:yyyy-MM-dd)_$(Hours)-$(Minutes)_$(Rev:rr)_$(Build.DefinitionName)

pool: MO360ComputePlatformAgentpoolNonprod

parameters:
  - name: repositoryname
    type: string
    default: TestRepo

### SAST
  - name: runsonarqube
    type: boolean
    default: false
  - name: runblackduck
    type: boolean
    default: false
  - name: runcredscan
    type: boolean
    default: false
  - name: doblackduckrapidscan
    type: boolean
    default: false
  - name: solution # Relative path from repo root of the solution(s) or MSBuild project to run. 
    type: string
    default: '**/*.sln'
### Deployment Options
  - name: RunDeployment
    displayName: Run Deployment
    type: boolean 
    default: true

### Build Options
  - name: buildPlatform # Specify the platform you want to build such as Win32, x86, x64 or any cpu.
    type: string
    default: 'Any CPU'
  - name: buildConfiguration # Specify the configuration you want to build such as debug or release.
    type: string
    values:
      - Debug
      - Release
    default: 'Release'
  - name: sdkVersion
    type: string
    default: '5.x' 
  - name: NugetServiceConnection
    type: string
    default: MO360ComputePlatformArtifactoryConnection
  - name: nugetConfigPath
    type: string
    default: 'NuGet.config'
    

       
steps:   

  - task: ArtifactoryNuGet@2
    inputs:
        command: 'restore'
        artifactoryService: ${{ parameters.NugetServiceConnection}}
        #artifactoryService: 'DEVOPS-JFROG-PID4C83'
        targetResolveRepo: 'nuget-opensource-virtual'
        solutionPath: '${{parameters.solution}}'
        nugetProtocolVersion: 'v3'